### ISSUE TITLE
Compute Head and Tail Prediction on FB15K dataset 

### ISSUE THREAD

**Issue by MuhibKhan** [luigiba/OpenKEonSpark#1]
I want to check the Prediction Head and Prediction Tail (Hits@10) on different types of relation like 1-to-1, 1-to-N, N-to-1 and N-to-N of TransD model like the results mentioned in the paper. How can I perform the Head and Tail Prediction on 1-to-1, 1-to-N, N-to-1 and N-to-N of relations of FB15k dataset?

![TransD](https://user-images.githubusercontent.com/7377986/68991363-09767c80-0899-11ea-928c-119703bcb060.png)

**Comment by luigiba** [comment]
You can refer to the script _n-n.py_ available in the original OpenKE repository to generate the files containing the test triples divided into 1-to-1, 1-to-N, N-to-1, N-to-N. https://github.com/thunlp/OpenKE/blob/master/benchmarks/FB15K/n-n.py

**Comment by MuhibKhan** [comment]
@luigiba Sir, I follow these steps:

- I create the {1-1, 1-N, N-1, N-N} files via n-n.py, for each FB15K dataset. Roughly, {train2id, valid2id, test2id} -> dictionaries -> {type_constrain.txt, test2id}; {test2id, f(dictionaries)} -> {1-1, 1-n, n-1, n-n}.txt.
- 
- test2id.txt is used in Reader.h. I replace test2id.txt with 1-1.txt.

Thing which confuses me and I unable to understand, how I differentiate the Prediction of Head and Tail. For example, I change the test2id.txt in Reader.h with 1-1.txt and run it on my dataset. The result which I got after the train and test, what would it represent (prediction of head or prediction of tail)? The output result belongs to which? Prediction of Head or Prediction of Tail?

**Comment by luigiba** [comment]
The report that you should obtain after the evaluation of the link prediction task is the following (filled with the test results):

```
no type constraint results:
metric			MRR			MR			hit@10			hit@3			hit@1
l(raw)			
r(raw)
averaged(raw)

l(filter)
r(filter)
averaged(filter)


type constraint results:
metric			MRR			MR			hit@10			hit@3			hit@1
l(raw)
r(raw)
averaged(raw)

l(filter)
r(filter)
averaged(filter)
```

the rows "l(raw), l(filter)" denote the link prediction results for the left part of the triple (i.e. the head prediction results); the rows "r(raw), r(filter)" denote the link prediction results for the right part of the triple (i.e. the tail prediction results).
